server:
  port: 8082

spring:
  application:
    name: 'orders-service'

  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null

  datasource:
    driver-class-name: org.h2.Driver
    platform: h2
    url: jdbc:h2:mem:orders;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: aVeryComplexPassword
    initialization-mode: never

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true

    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092