server:
  port: 8083

spring:
  application:
    name: 'shipping-service'

  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null

  kafka:
    bootstrap-servers: localhost:9092
