server:
  port: 8085

spring:
  application:
    name: 'product-service'

  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:orders;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: aVeryComplexPassword

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true

    open-in-view: false

  sql:
    init:
      platform: h2
      mode: embedded

# logging settings
logging:
  level:
    root: info
    com: warn
    org:
      apache: warn
      hibernate: warn
      springframework: warn

  pattern:
    #console: '%clr([%thread] [%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'
    console: '%clr([%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'